/* This should be generatd automatically in the future */

namespace RPG {

		public enum Skill {
			//SWORD COMBAT CATEGORY:
			COMBAT_SHORT_SWORD=0,
			COMBAT_LONG_SWORD,
			COMBAT_GREAT_SWORD,
			
			//AXE COMBAT CATEGORY:
			COMBAT_HAND_AXE,
			COMBAT_WAR_AXE,
			COMBAT_BIG_AXE,
			
			//BOW COMBAT CATEGORY:
			COMBAT_SHORT_BOW,
			COMBAT_LONG_BOW,
			
			//SHIELD COMBAT CATEGORY:
			COMBAT_SHIELD,
			
			OPEN_LOCKS,
			SET_REMOVE_TRAPS,
			TIE_KNOT,
			
			POTTERY,
			FORGE,
			JEWERLLY,
			QUARRY,
			CARPENTRY,
			FUR,
			TAILORING,
			
			//PLAY WIND INSTRUMENTS CATEGORY:
			PLAY_FLUTE,
			PLAY_OCARINA,
			PLAY_HORN,
			
			//PLAY STRING INSTRUMENTS CATEGORY:
			PLAY_HARP,
			PLAY_GUITAR,
			PLAY_LUTE,
			
			//PHYSICS KNOWLEDGE CATEGORY:
			KNOWLEDGE_SKY,
			KNOWLDGE_GEOGRAPHY,
			
			//BIOLOGICAL KNOWLEDGE CATEGORY:
			KNOWLEDGE_BOTANY,
			KNOWLEDGE_ZOOLOGY,
			KNOWLEDGE_VENOMS,
			
			//HUMAN KNOWLEDGE CATEGORY:
			KNOWLEDGE_HISTORY,
			KNOWLEDGE_POLITICS,
			KNOWLEDGE_TRADE,
			KNOWLEDGE_NAVIGATION,
			
			//RESISTANCE:
			RESISTANCE_COLD,
			RESISTANCE_HOT,
			RESISTANCE_TORTURE,
			RESISTANCE_VENOMS
			
		}

}
